<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>4. Error Handling &mdash; A Modern Introduction to Programming with JavaScript and jQuery</title>
    
    <link rel="stylesheet" href="_static/style.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    './',
        VERSION:     '1st Edition',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <link rel="copyright" title="Copyright" href="copyright.html" />
    <link rel="top" title="A Modern Introduction to Programming with JavaScript and jQuery" href="index.html" />
    <link rel="next" title="5. Web programming: A crash course" href="ch05.html" />
    <link rel="prev" title="3. Data structures: Objects and Arrays" href="ch03.html" /> 
  </head>
  <body>
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="ch05.html" title="5. Web programming: A crash course"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="ch03.html" title="3. Data structures: Objects and Arrays"
             accesskey="P">previous</a> |</li>
        <li><a href="index.html">A Modern Introduction to Programming with JavaScript and jQuery</a> &raquo;</li> 
      </ul>
    </div>

    <div class="document">
      <div class="documentwrapper">
          <div class="body">
            
  <div class="section" id="error-handling">
<span id="error-handling-chapter"></span><h1>4. Error Handling<a class="headerlink" href="#error-handling" title="Permalink to this headline">¶</a></h1>
<p>Writing programs that work when everything goes as expected is a good start.
Making your programs behave properly when encountering unexpected conditions is
where it really gets challenging.</p>
<p>The problematic situations that a program can encounter fall into two
categories: Programmer mistakes and genuine problems. If someone forgets to
pass a required argument to a function, that is an example of the first kind of
problem. On the other hand, if a program asks the user to enter a name and it
gets back an empty string, that is something the programmer can not prevent.</p>
<p>In general, one deals with programmer errors by finding and fixing them, and
with genuine errors by having the code check for them and perform some suitable
action to remedy them (for example, asking for the name again), or at least
fail in a well-defined and clean way.</p>
<div class="section" id="bugs-versus-exceptions">
<h2>4.1. Bugs versus exceptions<a class="headerlink" href="#bugs-versus-exceptions" title="Permalink to this headline">¶</a></h2>
<p>It is important to decide into which of these categories a certain problem
falls. For example, consider our old <tt class="docutils literal"><span class="pre">power</span></tt> function:</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="kd">function</span> <span class="nx">power</span><span class="p">(</span><span class="nx">base</span><span class="p">,</span> <span class="nx">exponent</span><span class="p">)</span> <span class="p">{</span>
    <span class="kd">var</span> <span class="nx">result</span> <span class="o">=</span> <span class="mi">1</span><span class="p">;</span>
    <span class="k">for</span> <span class="p">(</span><span class="kd">var</span> <span class="nx">count</span> <span class="o">=</span> <span class="mi">0</span><span class="p">;</span> <span class="nx">count</span> <span class="o">&lt;</span> <span class="nx">exponent</span><span class="p">;</span> <span class="nx">count</span><span class="o">++</span><span class="p">)</span>
        <span class="nx">result</span> <span class="o">*=</span> <span class="nx">base</span><span class="p">;</span>
    <span class="k">return</span> <span class="nx">result</span><span class="p">;</span>
<span class="p">}</span>
</pre></div>
</div>
<p>When some geek tries to call <tt class="docutils literal"><span class="pre">power(&quot;Rabbit&quot;,</span> <span class="pre">4)</span></tt>, that is quite obviously a
programmer error, but how about <tt class="docutils literal"><span class="pre">power(9,</span> <span class="pre">0.5)</span></tt>? The function can not handle
fractional exponents, but, mathematically speaking, raising a number to the
halfth power is perfectly reasonable (<tt class="docutils literal"><span class="pre">Math.pow</span></tt> can handle it). In
situations where it is not entirely clear what kind of input a function
accepts, it is often a good idea to explicitly state the kind of arguments that
are acceptable in a comment.</p>
<hr class="docutils" />
<p>If a function encounters a problem that it can not solve itself, what should it
do? In <a class="reference internal" href="ch03.html#objects-and-arrays-chapter"><em>Data structures: Objects and Arrays</em></a> we wrote the function <tt class="docutils literal"><span class="pre">between</span></tt>:</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="kd">function</span> <span class="nx">between</span><span class="p">(</span><span class="nx">string</span><span class="p">,</span> <span class="nx">start</span><span class="p">,</span> <span class="nx">end</span><span class="p">)</span> <span class="p">{</span>
    <span class="kd">var</span> <span class="nx">startAt</span> <span class="o">=</span> <span class="nx">string</span><span class="p">.</span><span class="nx">indexOf</span><span class="p">(</span><span class="nx">start</span><span class="p">)</span> <span class="o">+</span> <span class="nx">start</span><span class="p">.</span><span class="nx">length</span><span class="p">;</span>
    <span class="kd">var</span> <span class="nx">endAt</span> <span class="o">=</span> <span class="nx">string</span><span class="p">.</span><span class="nx">indexOf</span><span class="p">(</span><span class="nx">end</span><span class="p">,</span> <span class="nx">startAt</span><span class="p">);</span>
    <span class="k">return</span> <span class="nx">string</span><span class="p">.</span><span class="nx">slice</span><span class="p">(</span><span class="nx">startAt</span><span class="p">,</span> <span class="nx">endAt</span><span class="p">);</span>
<span class="p">}</span>
</pre></div>
</div>
<p>If the given <tt class="docutils literal"><span class="pre">start</span></tt> and <tt class="docutils literal"><span class="pre">end</span></tt> do not occur in the string, <tt class="docutils literal"><span class="pre">indexOf</span></tt> will
return <tt class="docutils literal"><span class="pre">-1</span></tt> and this version of <tt class="docutils literal"><span class="pre">between</span></tt> will return a lot of nonsense:
<tt class="docutils literal"><span class="pre">between(&quot;Your</span> <span class="pre">mother!&quot;,</span> <span class="pre">&quot;{-&quot;,</span> <span class="pre">&quot;-}&quot;)</span></tt> returns <tt class="docutils literal"><span class="pre">&quot;our</span> <span class="pre">mother&quot;</span></tt>.</p>
<p>When the program is running, and the function is called like that, the code
that called it will get a string value, as it expected, and happily continue
doing something with it. But the value is wrong, so whatever it ends up doing
with it will also be wrong. And if you are unlucky, this wrongness only causes
a problem after having passed through twenty other functions. In cases like
that, it is extremely hard to find out where the problem started.</p>
<p>In some cases, you will be so unconcerned about these problems that you don&#8217;t
mind the function misbehaving when given incorrect input.  For example, if you
know for sure the function will only be called from a few places, and you can
prove that these places give it decent input, it is generally not worth the
trouble to make the function bigger and uglier so that it can handle
problematic cases.</p>
<p>But most of the time, functions that fail &#8220;silently&#8221; are hard to use, and even
dangerous. What if the code calling <tt class="docutils literal"><span class="pre">between</span></tt> wants to know whether
everything went well? At the moment, it can not tell, except by re-doing all
the work that <tt class="docutils literal"><span class="pre">between</span></tt> did and checking the result of <tt class="docutils literal"><span class="pre">between</span></tt> with its
own result. That is bad. One solution is to make <tt class="docutils literal"><span class="pre">between</span></tt> return a special
value, such as <tt class="docutils literal"><span class="pre">false</span></tt> or <tt class="docutils literal"><span class="pre">undefined</span></tt>, when it fails.</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="kd">function</span> <span class="nx">between</span><span class="p">(</span><span class="nx">string</span><span class="p">,</span> <span class="nx">start</span><span class="p">,</span> <span class="nx">end</span><span class="p">)</span> <span class="p">{</span>
    <span class="kd">var</span> <span class="nx">startAt</span> <span class="o">=</span> <span class="nx">string</span><span class="p">.</span><span class="nx">indexOf</span><span class="p">(</span><span class="nx">start</span><span class="p">);</span>
    <span class="k">if</span> <span class="p">(</span><span class="nx">startAt</span> <span class="o">==</span> <span class="o">-</span><span class="mi">1</span><span class="p">)</span>
        <span class="k">return</span> <span class="kc">undefined</span><span class="p">;</span>
    <span class="nx">startAt</span> <span class="o">+=</span> <span class="nx">start</span><span class="p">.</span><span class="nx">length</span><span class="p">;</span>
    <span class="kd">var</span> <span class="nx">endAt</span> <span class="o">=</span> <span class="nx">string</span><span class="p">.</span><span class="nx">indexOf</span><span class="p">(</span><span class="nx">end</span><span class="p">,</span> <span class="nx">startAt</span><span class="p">);</span>
    <span class="k">if</span> <span class="p">(</span><span class="nx">endAt</span> <span class="o">==</span> <span class="o">-</span><span class="mi">1</span><span class="p">)</span>
        <span class="k">return</span> <span class="kc">undefined</span><span class="p">;</span>

    <span class="k">return</span> <span class="nx">string</span><span class="p">.</span><span class="nx">slice</span><span class="p">(</span><span class="nx">startAt</span><span class="p">,</span> <span class="nx">endAt</span><span class="p">);</span>
<span class="p">}</span>
</pre></div>
</div>
<p>You can see that error checking does not generally make functions prettier. But
now code that calls <tt class="docutils literal"><span class="pre">between</span></tt> can do something like:</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="kd">var</span> <span class="nx">input</span> <span class="o">=</span> <span class="nx">prompt</span><span class="p">(</span><span class="s2">&quot;Tell me something&quot;</span><span class="p">,</span> <span class="s2">&quot;&quot;</span><span class="p">);</span>
<span class="kd">var</span> <span class="nx">parenthesized</span> <span class="o">=</span> <span class="nx">between</span><span class="p">(</span><span class="nx">input</span><span class="p">,</span> <span class="s2">&quot;(&quot;</span><span class="p">,</span> <span class="s2">&quot;)&quot;</span><span class="p">);</span>
<span class="k">if</span> <span class="p">(</span><span class="nx">parenthesized</span> <span class="o">!=</span> <span class="kc">undefined</span><span class="p">)</span>
    <span class="nx">print</span><span class="p">(</span><span class="s2">&quot;You parenthesized &#39;&quot;</span><span class="p">,</span> <span class="nx">parenthesized</span><span class="p">,</span> <span class="s2">&quot;&#39;.&quot;</span><span class="p">);</span>
</pre></div>
</div>
<hr class="docutils" />
<p>In many cases returning a special value is a perfectly fine way to indicate an
error. It does, however, have its downsides. Firstly, what if the function can
already return every possible kind of value? For example, consider this
function that gets the last element from an array:</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="kd">function</span> <span class="nx">lastElement</span><span class="p">(</span><span class="nx">array</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="nx">array</span><span class="p">.</span><span class="nx">length</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">)</span>
        <span class="k">return</span> <span class="nx">array</span><span class="p">[</span><span class="nx">array</span><span class="p">.</span><span class="nx">length</span> <span class="o">-</span> <span class="mi">1</span><span class="p">];</span>
    <span class="k">else</span>
        <span class="k">return</span> <span class="kc">undefined</span><span class="p">;</span>
<span class="p">}</span>

<span class="nx">alert</span><span class="p">(</span><span class="nx">lastElement</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="kc">undefined</span><span class="p">]));</span>
</pre></div>
</div>
<p>So did the array have a last element? Looking at the value <tt class="docutils literal"><span class="pre">lastElement</span></tt>
returns, it is impossible to say.</p>
<p>The second issue with returning special values is that it can sometimes lead to
a whole lot of clutter. If a piece of code calls <tt class="docutils literal"><span class="pre">between</span></tt> ten times, it has
to check ten times whether <tt class="docutils literal"><span class="pre">undefined</span></tt> was returned. Also, if a function
calls <tt class="docutils literal"><span class="pre">between</span></tt> but does not have a strategy to recover from a failure, it
will have to check the return value of <tt class="docutils literal"><span class="pre">between</span></tt>, and if it is <tt class="docutils literal"><span class="pre">undefined</span></tt>,
this function can then return <tt class="docutils literal"><span class="pre">undefined</span></tt> or some other special value to its
caller, who in turn also checks for this value.</p>
<p>Sometimes, when something strange occurs, it would be practical to just stop
doing what we are doing and immediately jump back to a place that knows how to
handle the problem.</p>
<p>Well, we are in luck, a lot of programming languages provide such a thing.
Usually, it is called
<a class="reference external" href="http://en.wikipedia.org/wiki/Exception_handling">exception handling</a> and
the &#8220;bad&#8221; thing that occurs in the program is called an <strong>exception</strong>.</p>
</div>
<div class="section" id="try-throw-and-catch">
<span id="index-0"></span><h2>4.2. <tt class="docutils literal"><span class="pre">try</span></tt>, <tt class="docutils literal"><span class="pre">throw</span></tt> and <tt class="docutils literal"><span class="pre">catch</span></tt><a class="headerlink" href="#try-throw-and-catch" title="Permalink to this headline">¶</a></h2>
<p>The theory behind exception handling goes like this: It is possible for code to
raise (or throw) an exception, which is a value.  Raising an exception somewhat
resembles a super-charged return from a function ― it does not just jump out of
the current function, but also out of its callers, all the way up to the
top-level call that started the current execution. This is called unwinding the
stack.  You may remember the stack of function calls that was mentioned in
<a class="reference internal" href="ch02.html#functions-chapter"><em>Functions</em></a>. An exception zooms down this stack, throwing away all
the call contexts it encounters.</p>
<p>If they always zoomed right down to the base of the stack, exceptions would not
be of much use. They would just provide a novel way to blow up your program.
Fortunately, it is possible to set obstacles for exceptions along the stack.
These &#8216;catch&#8217; the exception as it is zooming down, and can do something with
it, after which the program continues running at the point where the
exception was caught.</p>
<p>An example:</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="kd">function</span> <span class="nx">lastElement</span><span class="p">(</span><span class="nx">array</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="nx">array</span><span class="p">.</span><span class="nx">length</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">)</span>
        <span class="k">return</span> <span class="nx">array</span><span class="p">[</span><span class="nx">array</span><span class="p">.</span><span class="nx">length</span> <span class="o">-</span> <span class="mi">1</span><span class="p">];</span>
    <span class="k">else</span>
        <span class="k">throw</span> <span class="s2">&quot;Can not take the last element of an empty array.&quot;</span><span class="p">;</span>
<span class="p">}</span>

<span class="kd">function</span> <span class="nx">lastElementPlusTen</span><span class="p">(</span><span class="nx">array</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">return</span> <span class="nx">lastElement</span><span class="p">(</span><span class="nx">array</span><span class="p">)</span> <span class="o">+</span> <span class="mi">10</span><span class="p">;</span>
<span class="p">}</span>

<span class="k">try</span> <span class="p">{</span>
    <span class="nx">alert</span><span class="p">(</span><span class="nx">lastElementPlusTen</span><span class="p">([]));</span>
<span class="p">}</span>
<span class="k">catch</span> <span class="p">(</span><span class="nx">error</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;Something went wrong: &quot;</span><span class="p">,</span> <span class="nx">error</span><span class="p">);</span>
<span class="p">}</span>
</pre></div>
</div>
<p><tt class="docutils literal"><span class="pre">throw</span></tt> is the keyword that is used to raise an exception. The keyword
<tt class="docutils literal"><span class="pre">try</span></tt> sets up an obstacle for exceptions: When the code in the block after it
raises an exception, the <tt class="docutils literal"><span class="pre">catch</span></tt> block will be executed. The variable named
in parentheses after the word <tt class="docutils literal"><span class="pre">catch</span></tt> is the name given to the exception
value inside this block.</p>
<p>Note that the function <tt class="docutils literal"><span class="pre">lastElementPlusTen</span></tt> completely ignores the
possibility that <tt class="docutils literal"><span class="pre">lastElement</span></tt> might go wrong. This is the big advantage of
exceptions ― error-handling code is only necessary at the point where the error
occurs, and the point where it is handled. The functions in between can forget
all about it.</p>
<p>Well, almost.</p>
<hr class="docutils" />
<p>Consider the following: A function <tt class="docutils literal"><span class="pre">processThing</span></tt> wants to set a top-level
variable <tt class="docutils literal"><span class="pre">currentThing</span></tt> to point to a specific thing while its body executes,
so that other functions can have access to that thing too. Normally you would
of course just pass the thing as an argument, but assume for a moment that that
is not practical.  When the function finishes, <tt class="docutils literal"><span class="pre">currentThing</span></tt> should be set
back to <tt class="docutils literal"><span class="pre">null</span></tt>.</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="kd">var</span> <span class="nx">currentThing</span> <span class="o">=</span> <span class="kc">null</span><span class="p">;</span>

<span class="kd">function</span> <span class="nx">processThing</span><span class="p">(</span><span class="nx">thing</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="nx">currentThing</span> <span class="o">!=</span> <span class="kc">null</span><span class="p">)</span>
        <span class="k">throw</span> <span class="s2">&quot;Oh no! We are already processing a thing!&quot;</span><span class="p">;</span>

    <span class="nx">currentThing</span> <span class="o">=</span> <span class="nx">thing</span><span class="p">;</span>
    <span class="cm">/* do complicated processing... */</span>
    <span class="nx">currentThing</span> <span class="o">=</span> <span class="kc">null</span><span class="p">;</span>
<span class="p">}</span>
</pre></div>
</div>
<p>But what if the complicated processing raises an exception? In that case the
call to <tt class="docutils literal"><span class="pre">processThing</span></tt> will be thrown off the stack by the exception, and
<tt class="docutils literal"><span class="pre">currentThing</span></tt> will never be reset to <tt class="docutils literal"><span class="pre">null</span></tt>.</p>
<p><tt class="docutils literal"><span class="pre">try</span></tt> statements can also be followed by a <tt class="docutils literal"><span class="pre">finally</span></tt> keyword, which means
&#8216;no matter <em>what</em> happens, run this code after trying to run the code in the
<tt class="docutils literal"><span class="pre">try</span></tt> block&#8217;. If a function has to clean something up, the cleanup code
should usually be put into a <tt class="docutils literal"><span class="pre">finally</span></tt> block:</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="kd">function</span> <span class="nx">processThing</span><span class="p">(</span><span class="nx">thing</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="nx">currentThing</span> <span class="o">!=</span> <span class="kc">null</span><span class="p">)</span>
        <span class="k">throw</span> <span class="s2">&quot;Oh no! We are already processing a thing!&quot;</span><span class="p">;</span>

    <span class="nx">currentThing</span> <span class="o">=</span> <span class="nx">thing</span><span class="p">;</span>
    <span class="k">try</span> <span class="p">{</span>
        <span class="cm">/* do complicated processing... */</span>
    <span class="p">}</span>
    <span class="k">finally</span> <span class="p">{</span>
        <span class="nx">currentThing</span> <span class="o">=</span> <span class="kc">null</span><span class="p">;</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></div>
</div>
<hr class="docutils" />
<p>A lot of errors in programs cause the JavaScript environment to raise an
exception. For example:</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="k">try</span> <span class="p">{</span>
    <span class="nx">alert</span><span class="p">(</span><span class="nx">Sasquatch</span><span class="p">);</span>
<span class="p">}</span>
<span class="k">catch</span> <span class="p">(</span><span class="nx">error</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">alert</span><span class="p">(</span><span class="s2">&quot;Caught: &quot;</span> <span class="o">+</span> <span class="nx">error</span><span class="p">.</span><span class="nx">message</span><span class="p">);</span>
<span class="p">}</span>
</pre></div>
</div>
<p>In cases like this, special error objects are raised. These always have a
<tt class="docutils literal"><span class="pre">message</span></tt> property containing a description of the problem. You can raise
similar objects using the <tt class="docutils literal"><span class="pre">new</span></tt> keyword and the <tt class="docutils literal"><span class="pre">Error</span></tt> constructor:</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="s2">&quot;Fire!&quot;</span><span class="p">);</span>
</pre></div>
</div>
<hr class="docutils" />
<p>When an exception goes all the way to the bottom of the stack without being
caught, it gets handled by the environment. What this means differs between the
different browsers, sometimes a description of the error is written to some
kind of log, sometimes a window pops up describing the error.</p>
<p>The errors produced by entering code in the console on this page are always
caught by the console, and displayed among the other output.</p>
<hr class="docutils" />
<p>Most programmers consider exceptions purely an error-handling mechanism. In
essence, though, they are just another way of influencing the control flow of a
program. For example, they can be used as a kind of <tt class="docutils literal"><span class="pre">break</span></tt> statement in a
recursive function. Here is a slightly strange function which determines
whether an object, and the objects stored inside it, contain at least seven
<tt class="docutils literal"><span class="pre">true</span></tt> values:</p>
<div class="highlight-javascript"><div class="highlight"><pre><span class="kd">var</span> <span class="nx">FoundSeven</span> <span class="o">=</span> <span class="p">{};</span>

<span class="kd">function</span> <span class="nx">hasSevenTruths</span><span class="p">(</span><span class="nx">object</span><span class="p">)</span> <span class="p">{</span>
    <span class="kd">var</span> <span class="nx">counted</span> <span class="o">=</span> <span class="mi">0</span><span class="p">;</span>

    <span class="kd">function</span> <span class="nx">count</span><span class="p">(</span><span class="nx">object</span><span class="p">)</span> <span class="p">{</span>
        <span class="k">for</span> <span class="p">(</span><span class="kd">var</span> <span class="nx">name</span> <span class="k">in</span> <span class="nx">object</span><span class="p">)</span> <span class="p">{</span>
            <span class="k">if</span> <span class="p">(</span><span class="nx">object</span><span class="p">[</span><span class="nx">name</span><span class="p">]</span> <span class="o">===</span> <span class="kc">true</span><span class="p">)</span> <span class="p">{</span>
                <span class="nx">counted</span><span class="o">++</span><span class="p">;</span>
                <span class="k">if</span> <span class="p">(</span><span class="nx">counted</span> <span class="o">==</span> <span class="mi">7</span><span class="p">)</span>
                    <span class="k">throw</span> <span class="nx">FoundSeven</span><span class="p">;</span>
            <span class="p">}</span>
            <span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="k">typeof</span> <span class="nx">object</span><span class="p">[</span><span class="nx">name</span><span class="p">]</span> <span class="o">==</span> <span class="s2">&quot;object&quot;</span><span class="p">)</span> <span class="p">{</span>
                <span class="nx">count</span><span class="p">(</span><span class="nx">object</span><span class="p">[</span><span class="nx">name</span><span class="p">]);</span>
           <span class="p">}</span>
        <span class="p">}</span>
      <span class="p">}</span>

      <span class="k">try</span> <span class="p">{</span>
          <span class="nx">count</span><span class="p">(</span><span class="nx">object</span><span class="p">);</span>
          <span class="k">return</span> <span class="kc">false</span><span class="p">;</span>
      <span class="p">}</span>
      <span class="k">catch</span> <span class="p">(</span><span class="nx">exception</span><span class="p">)</span> <span class="p">{</span>
          <span class="k">if</span> <span class="p">(</span><span class="nx">exception</span> <span class="o">!=</span> <span class="nx">FoundSeven</span><span class="p">)</span>
              <span class="k">throw</span> <span class="nx">exception</span><span class="p">;</span>
          <span class="k">return</span> <span class="kc">true</span><span class="p">;</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></div>
</div>
<p>The inner function <tt class="docutils literal"><span class="pre">count</span></tt> is recursively called for every object that is
part of the argument. When the variable <tt class="docutils literal"><span class="pre">counted</span></tt> reaches seven, there is no
point in continuing to count, but just returning from the current call to
<tt class="docutils literal"><span class="pre">count</span></tt> will not necessarily stop the counting, since there might be more
calls below it. So what we do is just throw a value, which will cause the
control to jump right out of any calls to <tt class="docutils literal"><span class="pre">count</span></tt>, and land at the <tt class="docutils literal"><span class="pre">catch</span></tt>
block.</p>
<p>But just returning <tt class="docutils literal"><span class="pre">true</span></tt> in case of an exception is not correct.  Something
else might be going wrong, so we first check whether the exception is the
object <tt class="docutils literal"><span class="pre">FoundSeven</span></tt>, created specifically for this purpose. If it is not,
this <tt class="docutils literal"><span class="pre">catch</span></tt> block does not know how to handle it, so it raises it again.</p>
<p>This is a pattern that is also common when dealing with error conditions ― you
have to make sure that your <tt class="docutils literal"><span class="pre">catch</span></tt> block only handles exceptions that it
knows how to handle. Throwing string values, as some of the examples in this
chapter do, is rarely a good idea, because it makes it hard to recognise the
type of the exception. A better idea is to use unique values, such as the
<tt class="docutils literal"><span class="pre">FoundSeven</span></tt> object, or to introduce a new type of objects, as described in
<a class="reference internal" href="ch11.html#oop-chapter"><em>Object-oriented Programming</em></a>.</p>
</div>
<div class="section" id="glossary">
<h2>4.3. Glossary<a class="headerlink" href="#glossary" title="Permalink to this headline">¶</a></h2>
<dl class="glossary docutils">
<dt id="term-exception">exception</dt>
<dd>A special condition (usually a bad one) that alters the normal flow
of execution of a program.</dd>
<dt id="term-exception-handling">exception handling</dt>
<dd>A programming language construct used to handle special conditions
(exceptions) that alter the normal control flow of a program.</dd>
</dl>
</div>
<div class="section" id="exercises">
<h2>4.4. Exercises<a class="headerlink" href="#exercises" title="Permalink to this headline">¶</a></h2>
<ul class="simple">
<li><a class="reference internal" href="exercises/ch04/ch04s01.html#ch04s01"><em>Chapter 4 Exercise Set 1</em></a></li>
</ul>
</div>
</div>


          </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="ch05.html" title="5. Web programming: A crash course"
             >next</a> |</li>
        <li class="right" >
          <a href="ch03.html" title="3. Data structures: Objects and Arrays"
             >previous</a> |</li>
        <li><a href="index.html">A Modern Introduction to Programming with JavaScript and jQuery</a> &raquo;</li> 
      </ul>
    </div>
    <div class="footer">
        &copy; <a href="copyright.html">Copyright</a> 2013, Marijn Haverbeke and Jeffrey Elkner.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.2.2.
    </div>
  </body>
</html>